export default [
  { name: 'name',
    required: true,
    label: '姓名',
    align: 'left',
    field: row => row.name,
    format: val => `${val}`,
    sortable: true },
  { name: 'sum_of_paid',
    required: true,
    label: '缴费总金额',
    align: 'left',
    field: row => row.sum_of_paid ? row.sum_of_paid : 0,
    format: val => `￥${val}`,
    sortable: true,
    sort: (a, b, rowA, rowB) => parseInt(a * 100, 10) - parseInt(b * 100, 10)
  },
  { name: 'latest_paid_amount',
    required: true,
    label: '最近缴费额',
    align: 'left',
    field: row => row.latest_paid_amount,
    format: val => `￥${val}`,
    sortable: true,
    sort: (a, b, rowA, rowB) => parseInt(a * 100, 10) - parseInt(b * 100, 10)
  },
  { name: 'latest_paid_course',
    required: true,
    label: '最近缴费课程数',
    align: 'left',
    field: row => row.latest_paid_course,
    format: val => `${val}节课`,
    sortable: true },
  { name: 'latest_paid_time',
    required: true,
    label: '最近缴费时间',
    align: 'left',
    field: row => row.latest_paid_time,
    sortable: true },
  { name: 'duration',
    required: true,
    label: '距离当前天数',
    align: 'left',
    field: row => row.duration,
    format: val => `${val}天`,
    sortable: true },
  { name: 'teacher',
    required: true,
    label: '老师',
    align: 'left',
    field: row => row.teacher,
    sortable: true }
]
// 'number_of_month','amount','create_time','student'
