export default [
  { name: 'id',
    required: true,
    label: '序号',
    align: 'left',
    field: row => row.id,
    format: val => `${val}`,
    style: 'max-width: 20px',
    sortable: true },
  { name: 'course',
    required: true,
    label: '缴费课程数',
    align: 'left',
    field: row => row.number_of_course,
    format: val => `${val}节`,
    sortable: true },
  { name: 'amount',
    required: true,
    label: '金额',
    align: 'left',
    field: row => row.amount,
    format: val => `￥${val}`,
    sortable: true,
    sort: (a, b, rowA, rowB) => parseInt(a * 100, 10) - parseInt(b * 100, 10)
  },
  { name: 'time',
    required: true,
    label: '缴费时间',
    align: 'left',
    field: row => row.create_time,
    sortable: true },
  { name: 'remarks',
    required: true,
    label: '备注',
    align: 'left',
    field: row => row.remarks ? row.remarks : '无',
    sortable: true },
  { name: 'student',
    required: true,
    label: '学生',
    align: 'left',
    field: row => row.student,
    sortable: true }
]
